apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::227071492203:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OFFBKTC80BZG
      username: system:node:{{EC2PrivateDNSName}}
     - groups:
      - system:masters
      rolearn: arn:aws:iam::227071492203:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-26T19:09:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1468"
  uid: c0499580-f6d1-4c64-a123-85bbfbac1c6e
